### ISSUE TITLE
add new environment not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#319]
When I try to add a new environment, the details form is showing empty and fields are not visible.
![image](https://user-images.githubusercontent.com/11614204/97535578-dc57a700-19e1-11eb-9e8e-a6006fa05d5b.png)

**Comment by piyush94** [comment]
Error in the log when I click on Add button, not sure if it's related to this issue.
```
com.impossibl.postgres.jdbc.PGSQLSimpleException: column a.lineno does not exist
After GetParentDomains, m_domains.size()=1
m_parentdomains=1
        at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
        at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:447)
        at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:209)
        at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:199)
        at com.impossibl.postgres.jdbc.PGConnectionImpl.getCachedStatement(PGConnectionImpl.java:1363)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.parseIfNeeded(PGPreparedStatement.java:199)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:268)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:289)
        at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:96)
        at dmadmin.util.DynamicQueryBuilder.executeQuery(DynamicQueryBuilder.java:148)
        at dmadmin.DMSession.getHistoryNewsForObject(DMSession.java:12015)
        at dmadmin.NewsFeed.doGetNotes(NewsFeed.java:248)
        at dmadmin.NewsFeed.handleRequest(NewsFeed.java:93)
        at dmadmin.JSONMultipartServletBase.internalHandleRequest(JSONMultipartServletBase.java:154)
        at dmadmin.JSONMultipartServletBase.doGet(JSONMultipartServletBase.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Unable to retrieve history from database
        at dmadmin.DMSession.getHistoryNewsForObject(DMSession.java:12147)
        at dmadmin.NewsFeed.doGetNotes(NewsFeed.java:248)
        at dmadmin.NewsFeed.handleRequest(NewsFeed.java:93)
        at dmadmin.JSONMultipartServletBase.internalHandleRequest(JSONMultipartServletBase.java:154)
        at dmadmin.JSONMultipartServletBase.doGet(JSONMultipartServletBase.java:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
{"result":false,"error":"Unable to retrieve history from database"}
```

**Comment by sbtaylor15** [comment]
What is your database schema version?  Run - select * from dm.dm_tableinfo;
Looks like a database update was skipped for some reason.

Thanks, Steve

CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106


*Book at time slot with us
<https://www.deployhub.com/devops-experts-just-clicks-away/>*

Follow us on: Blog <https://www.deployhub.com/category/featured/> / Twitter
<https://twitter.com/@deployhubproj>/ Facebook
<https://www.facebook.com/groups/DeployHubProject/?ref=bookmarks> / LinkedIn
<https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UC7jomcQ2D4VgjGV2ePtKWfA>
*Achieve Fast, Agentless, and Safe Continuous Deployments with DeployHub*

**Comment by piyush94** [comment]
Version details,
Version    9.0.0
Build    20201023_1969
Database Schema    2020100804

**Comment by sbtaylor15** [comment]
@piyush94 did some digging and it looks like a query was skipped.  Ca you run these statements against the db and try creating an environment to see if the issue is resolved?

alter table dm.dm_historyattachment add IF NOT EXISTS line character varying(4096);
alter table dm.dm_historyattachment add IF NOT EXISTS lineno integer;

**Comment by piyush94** [comment]
Thanks @sbtaylor15 , issue is fixed now.
