### ISSUE TITLE
add component form not opening

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#322]
After clicking on the Add button on the components page, the component details form doesn't open.
logs:
```
returning ret size=3
c) true (group *EVERYONE*)
java.lang.NullPointerException
        at dmadmin.model.Component.getSummaryJSON(Component.java:212)
        at dmadmin.GetSummaryData.handleRequest(GetSummaryData.java:170)
        at dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:106)
        at dmadmin.HttpServletBase.doGet(HttpServletBase.java:53)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
connectToDatabase()
```

Version | 8.0.1
Build | 20201124_1981
Database Schema: | 2020100804

**Comment by sbtaylor15** [comment]
Can you please send a screen shot?  I need to see which pieces of the page have been rendered, ie drop downs etc.

**Comment by piyush94** [comment]
The complete form itself isn't rendered. Just on the top right corner it says New component base version.

**Comment by sbtaylor15** [comment]
We are able to recreate the issue and working on a fix.

**Comment by sbtaylor15** [comment]
Here is the fix - quay.io/deployhub/deployhub-pro:master-v9.0.0.2929-gf28bf8b

**Comment by piyush94** [comment]
Thanks, the add component form is now working.
