### ISSUE TITLE
deployment not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#324]
logs:
```
Sending request to Trilogy Server on hostname docker_dhpro
Setting output stream, waitFor = false
server is [docker_dhpro]
Connecting to docker_dhpro:2305...
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at java.net.Socket.<init>(Socket.java:452)
        at java.net.Socket.<init>(Socket.java:229)
        at com.openmakesoftware.trilogy.TrilogyLib.establishOutgoingConnection(TrilogyLib.java:219)
        at com.openmakesoftware.trilogy.TrilogyLib.connectToServer(TrilogyLib.java:276)
        at com.openmakesoftware.trilogy.TrilogyLib.sendRunRequest(TrilogyLib.java:553)
        at dmadmin.util.CommandLine.runWithTrilogy(CommandLine.java:242)
        at dmadmin.model.TaskDeploy.startDeployment(TaskDeploy.java:150)
        at dmadmin.model.TaskDeploy.run(TaskDeploy.java:117)
        at dmadmin.RunTask.handleRun(RunTask.java:564)
        at dmadmin.RunTask.handleRequest(RunTask.java:179)
        at dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:106)
        at dmadmin.HttpServletBase.doGet(HttpServletBase.java:53)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
{"error":"Failed to start deployment\nConnection to TrilogyServer process refused - TrilogyServer process running?"}
```

Docker container hostname is set to docker_dhpro

I don't see any process listening on 2305
```
[omreleng@docker_dhpro deployhub]$ sudo netstat -tlnup
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.11:34641        0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::5432                 :::*                    LISTEN      -                   
udp        0      0 127.0.0.11:40758        0.0.0.0:*                           -
```

**Comment by piyush94** [comment]
container startup logs:
```
sudo chown -R postgres:postgres /var/lib/pgsql
+ sudo chmod -R 777 /opt/deployhub
+ pkill postgres
+ sudo test -f /var/lib/pgsql/data/pg_hba.conf
+ echo 'Database already initialized'
+ sudo -u postgres /usr/pgsql-10/bin/pg_ctl start --pgdata=/var/lib/pgsql/data
Database already initialized
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....2020-12-21 08:16:30.143 UTC [16] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2020-12-21 08:16:30.143 UTC [16] LOG:  listening on IPv6 address "::", port 5432
2020-12-21 08:16:30.163 UTC [16] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2020-12-21 08:16:30.183 UTC [16] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2020-12-21 08:16:30.203 UTC [16] LOG:  redirecting log output to logging collector process
2020-12-21 08:16:30.203 UTC [16] HINT:  Future log output will appear in directory "log".
 done
server started
+ sleep 10
+ sudo -u postgres /usr/pgsql-10/bin/pg_ctl status --pgdata=/var/lib/pgsql/data
pg_ctl: server is running (PID: 16)
/usr/pgsql-10/bin/postgres "-D" "/var/lib/pgsql/data"
+ '[' '!' -e /opt/deployhub/logs ']'
+ sudo chmod -R 777 /opt/deployhub
+ sudo chown -R omreleng /opt/deployhub
+ cd /opt/deployhub/engine
+ export LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ LD_LIBRARY_PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin
+ export PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
+ PATH=/opt/deployhub/engine/lib:/opt/deployhub/engine/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/google-cloud-sdk/bin:/usr/pgsql-10/bin:/usr/local/google-cloud-sdk/bin
++ cut -d: -f6
+++ whoami
++ getent passwd omreleng
+ export HOME=/home/omreleng
+ HOME=/home/omreleng
+ sudo cp -r /keys/cloudforte.pem /keys/dh-aws.pem /keys/dh.pem /keys/ec2-18-221-152-62.pem /keys/test-key-pair.pem /root/.ssh
+ sudo chown -R root /root/.ssh
+ sudo chmod 755 /root/.ssh
+ '[' -e /root/.ssh/known_hosts ']'
+ cp -r /keys/cloudforte.pem /keys/dh-aws.pem /keys/dh.pem /keys/ec2-18-221-152-62.pem /keys/test-key-pair.pem /home/omreleng/.ssh
+ chown -R omreleng /home/omreleng/.ssh
+ chmod 755 /home/omreleng/.ssh
+ chmod 600 '/home/omreleng/.ssh/known*'
chmod: cannot access '/home/omreleng/.ssh/known*': No such file or directory
+ echo Running DeployHub Processes
Running DeployHub Processes
+ java -jar /opt/deployhub/webadmin/webapp-runner.jar --path /dmadminweb /opt/deployhub/webadmin/deployhub-webadmin.war
```

**Comment by piyush94** [comment]
`/opt/deployhub/engine/trilogyd: No such file or directory` when i try manually run.

**Comment by sbtaylor15** [comment]
Hi Piyush,

What is the docket tag associated with the image you are running.  We removed the dependency on Trilogy.  Should be skipping the call to Trilogy as part of the deploy process and go directly against the dm executable.

**Comment by piyush94** [comment]
Hi Steve,

This the tag for build I'm using. master-v9.0.0.2929-gf28bf8b

**Comment by piyush94** [comment]
Not able to save credentials as well.
```
Connecting to docker_dhpro:2305...
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at java.net.Socket.connect(Socket.java:556)
        at java.net.Socket.<init>(Socket.java:452)
        at java.net.Socket.<init>(Socket.java:229)
        at com.openmakesoftware.trilogy.TrilogyLib.establishOutgoingConnection(TrilogyLib.java:219)
        at com.openmakesoftware.trilogy.TrilogyLib.connectToServer(TrilogyLib.java:276)
        at com.openmakesoftware.trilogy.TrilogyLib.sendRunRequest(TrilogyLib.java:553)
        at dmadmin.util.CommandLine.runWithTrilogy(CommandLine.java:242)
        at dmadmin.model.Engine.encryptValue(Engine.java:376)
        at dmadmin.DMSession.processField(DMSession.java:31112)
        at dmadmin.UpdateSummaryData.handleRequest(UpdateSummaryData.java:89)
        at dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:106)
        at dmadmin.HttpServletBase.doPost(HttpServletBase.java:61)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Encryption Failed for **<SOME_PASSWORD_HERE>**
        at dmadmin.model.Engine.encryptValue(Engine.java:380)
        at dmadmin.DMSession.processField(DMSession.java:31112)
        at dmadmin.UpdateSummaryData.handleRequest(UpdateSummaryData.java:89)
        at dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:106)
        at dmadmin.HttpServletBase.doPost(HttpServletBase.java:61)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by sbtaylor15** [comment]
Credentials are encrypted using the dm executable.  We have figured out what is happening and in the process of publishing an update.

**Comment by sbtaylor15** [comment]
We believe that the issue has been resolved for both the deployment and credential failure.  Please use tag quay.io/deployhub/deployhub-pro:master-v9.0.0.2935-g718ce8f.  Let us know what happens on your side.

**Comment by piyush94** [comment]
Deployments from proxy are now not working.
error:
```
2020-12-24 09:40:55,107 - Thread-1 - Username must be specified
```

**Comment by sbtaylor15** [comment]
master-v9.0.0.2936-gbeafac4 will fix the proxy issue with the missing userid.

**Comment by sbtaylor15** [comment]
Need to look at the list of environment not showing up.  We think your database schema maybe slightly out of sync with the code.

**Comment by sbtaylor15** [comment]
@piyush94 did the new proxy fix the issue?

**Comment by piyush94** [comment]
@sbtaylor15 i think issue was resolved when i used this UI tag master-v9.0.0.2936-gbeafac4. Forgot to close this. 

I was trying new proxy because old proxy is based of fedora 28 which is quite old and i was not able to install some newer packages using yum.

**Comment by sbtaylor15** [comment]
@piyush94 fyi, we have moved to Fedora 32 for all of the images.

**Comment by piyush94** [comment]
@sbtaylor15 yes, noticed that in the new images. Thanks.
