### ISSUE TITLE
endpoint ping not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#331]
In both the images, this error is coming in the logs,
```
Thu Feb 18 08:42:53 2021: Capturing output
Thu Feb 18 08:42:53 2021: ping: socket: Operation not permitted
Thu Feb 18 08:42:53 2021: Waiting for command to complete
Thu Feb 18 08:42:53 2021: Exit Code: 0
```

**Comment by sbtaylor15** [comment]
Some reason it needs to be run via sudo.  Let us look into it.

**Comment by piyush94** [comment]
Will this cause any issue with deployments?

**Comment by sbtaylor15** [comment]
No, the ping is just used for the Test Connection for a server.  We have found a solution and are in the process of rebuilding the images to pick up the change.

**Comment by sbtaylor15** [comment]
@piyush94 we have fixed this for the latest ui.  Please pull tag: ui-skin-v9.0.0.3115-gf6cb9d1

**Comment by piyush94** [comment]
@sbtaylor15 Thanks ping works now. Could you please add this to old UI as well?

Also, I am seeing this jdbc error in the logs,
```
com.impossibl.postgres.jdbc.PGSQLSimpleException: column a.lineno does not exist
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:447)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:209)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement$1.call(PGPreparedStatement.java:199)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGConnectionImpl.getCachedStatement(PGConnectionImpl.java:1363)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement.parseIfNeeded(PGPreparedStatement.java:199)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:268)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:289)
Tue Mar  2 09:18:39 2021:       at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:96)
Tue Mar  2 09:18:39 2021:       at dmadmin.util.DynamicQueryBuilder.executeQuery(DynamicQueryBuilder.java:148)
Tue Mar  2 09:18:39 2021:       at dmadmin.DMSession.getPendingNewsForObject(DMSession.java:12283)
Tue Mar  2 09:18:39 2021:       at dmadmin.NewsFeed.doGetNotes(NewsFeed.java:244)
Tue Mar  2 09:18:39 2021:       at dmadmin.NewsFeed.handleRequest(NewsFeed.java:93)
Tue Mar  2 09:18:39 2021:       at dmadmin.JSONMultipartServletBase.internalHandleRequest(JSONMultipartServletBase.java:154)
Tue Mar  2 09:18:39 2021:       at dmadmin.JSONMultipartServletBase.doGet(JSONMultipartServletBase.java:81)
Tue Mar  2 09:18:39 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
Tue Mar  2 09:18:39 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Tue Mar  2 09:18:39 2021:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Tue Mar  2 09:18:39 2021:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Tue Mar  2 09:18:39 2021:       at java.lang.Thread.run(Thread.java:748)
Tue Mar  2 09:18:39 2021: java.lang.RuntimeException: Unable to retrieve pending news from database
Tue Mar  2 09:18:39 2021:       at dmadmin.DMSession.getPendingNewsForObject(DMSession.java:12341)
Tue Mar  2 09:18:39 2021:       at dmadmin.NewsFeed.doGetNotes(NewsFeed.java:244)
Tue Mar  2 09:18:39 2021:       at dmadmin.NewsFeed.handleRequest(NewsFeed.java:93)
Tue Mar  2 09:18:39 2021:       at dmadmin.JSONMultipartServletBase.internalHandleRequest(JSONMultipartServletBase.java:154)
Tue Mar  2 09:18:39 2021:       at dmadmin.JSONMultipartServletBase.doGet(JSONMultipartServletBase.java:81)
Tue Mar  2 09:18:39 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
Tue Mar  2 09:18:39 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
Tue Mar  2 09:18:39 2021:       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
Tue Mar  2 09:18:39 2021:       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Tue Mar  2 09:18:39 2021:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Tue Mar  2 09:18:39 2021:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Tue Mar  2 09:18:39 2021:       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Tue Mar  2 09:18:39 2021:       at java.lang.Thread.run(Thread.java:748)
Tue Mar  2 09:18:39 2021: {"result":false,"error":"Unable to retrieve pending news from database"}
```
