### ISSUE TITLE
object filter columns schema update

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#334]
Kindly add the schema updates for filter columns in the docker image. I got this error in the new build, ui-skin-v9.0.0.3115-gf6cb9d1
```
Tue Mar  2 09:18:36 2021: com.impossibl.postgres.jdbc.PGSQLSimpleException: column "endpointfilter" does not exist
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:447)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.PGSimpleStatement.prepare(PGSimpleStatement.java:80)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:104)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.PGSimpleStatement.execute(PGSimpleStatement.java:125)
Tue Mar  2 09:18:36 2021:       at com.impossibl.postgres.jdbc.PGSimpleStatement.executeQuery(PGSimpleStatement.java:176)
Tue Mar  2 09:18:36 2021:       at dmadmin.DMSession.getTableFilter(DMSession.java:29460)
Tue Mar  2 09:18:36 2021:       at dmadmin.TableFilter.doGet(TableFilter.java:63)
Tue Mar  2 09:18:36 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
Tue Mar  2 09:18:36 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
Tue Mar  2 09:18:36 2021:       at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
Tue Mar  2 09:18:36 2021:       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
Tue Mar  2 09:18:36 2021:       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
Tue Mar  2 09:18:36 2021:       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
Tue Mar  2 09:18:36 2021:       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
Tue Mar  2 09:18:36 2021:       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Tue Mar  2 09:18:36 2021:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Tue Mar  2 09:18:36 2021:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Tue Mar  2 09:18:36 2021:       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Tue Mar  2 09:18:36 2021:       at java.lang.Thread.run(Thread.java:748)
```

**Comment by sbtaylor15** [comment]
Fixed in quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3117-gceaf191
