### ISSUE TITLE
synchronize module not working in dh2helm

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#340]
Synchronize module is not copying back the helm template file to the DeployHub container to be used in helm capture step.
Changing it to copy module is working.
```
        fp_task.write("  - name: helm template\n")
        fp_task.write('    shell: ' + helm_exe + ' template ' + chartname + ' ' + namespace + ' ' + helmtemplateopts + ' -f ' + chartvalues + "\n")
        fp_task.write("    args:\n")
        fp_task.write("      chdir: " + to_dir + "\n")
        fp_task.write("    changed_when: False\n")
        fp_task.write("    register: myshell_output\n")
        fp_task.write("  - name: copy the output to a local file\n")
        fp_task.write("    copy:\n")                                                            <----- here, changed from synchronize
        fp_task.write("      content: \"{{ myshell_output.stdout }}\"\n")
        fp_task.write("      dest: \"" + to_dir + ".yml\"\n")
        fp_task.write("    delegate_to: localhost\n")
```

Error:
```
cat: /tmp/dh1625485107455.yml: No such file or directory
```

Stacktrace:
```
Traceback (most recent call last):
  File "/opt/deployhub/engine/scripts/dh2helm.py", line 437, in 
    main()
  File "/opt/deployhub/engine/scripts/dh2helm.py", line 422, in main
    upload_helm(override, chartvalues, newvals, to_dir + ".yml")
  File "/opt/deployhub/engine/scripts/dh2helm.py", line 115, in upload_helm
    dobj = json.loads(jstr)
  File "/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sbtaylor15** [comment]
Fixed in  ui-skin-v9.0.0.3177-gb251f32
