### ISSUE TITLE
test connection not working

### ISSUE THREAD

**Issue by piyush94** [DeployHubProject/DeployHub-Pro#349]
LDAP user:
```
Wed Sep 15 07:27:34 2021: url=TestServerConnection?id=122
Wed Sep 15 07:27:34 2021: testing server 122
Wed Sep 15 07:27:34 2021: GetUserName - m_userID=296
Wed Sep 15 07:27:34 2021: Running: "dm" "-usr" "sohalpiy" "-checkserver" "122" 
Wed Sep 15 07:27:34 2021: Running: "dm" "-usr" "sohalpiy" "-checkserver" "122" 
Wed Sep 15 07:27:34 2021: java.lang.NullPointerException
Wed Sep 15 07:27:34 2021:       at java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
Wed Sep 15 07:27:34 2021:       at java.lang.ProcessEnvironment.access$400(ProcessEnvironment.java:61)
Wed Sep 15 07:27:34 2021:       at java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
Wed Sep 15 07:27:34 2021:       at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
Wed Sep 15 07:27:34 2021:       at java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
Wed Sep 15 07:27:34 2021:       at dmadmin.util.CommandLine.run(CommandLine.java:131)
Wed Sep 15 07:27:34 2021:       at dmadmin.util.CommandLine.runWithTrilogy(CommandLine.java:215)
Wed Sep 15 07:27:34 2021:       at dmadmin.TestServerConnection.handleRequest(TestServerConnection.java:64)
Wed Sep 15 07:27:34 2021:       at dmadmin.HttpServletBase.internalHandleRequest(HttpServletBase.java:99)
Wed Sep 15 07:27:34 2021:       at dmadmin.HttpServletBase.doGet(HttpServletBase.java:46)
Wed Sep 15 07:27:34 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
Wed Sep 15 07:27:34 2021:       at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
Wed Sep 15 07:27:34 2021:       at org.apache.catalina.connector.CoyoteAd
apter.service(CoyoteAdapter.java:342)
Wed Sep 15 07:27:34 2021:       at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
Wed Sep 15 07:27:34 2021:       at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
Wed Sep 15 07:27:34 2021:       at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
Wed Sep 15 07:27:34 2021:       at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457)
Wed Sep 15 07:27:34 2021:       at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
Wed Sep 15 07:27:34 2021:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Wed Sep 15 07:27:34 2021:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Wed Sep 15 07:27:34 2021:       at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Wed Sep 15 07:27:34 2021:       at java.lang.Thread.run(Thread.java:748)
```

admin user:
```
Wed Sep 15 07:29:23 2021: url=TestServerConnection?id=122
Wed Sep 15 07:29:23 2021: testing server 122
Wed Sep 15 07:29:23 2021: GetUserName - m_userID=1
Wed Sep 15 07:29:23 2021: Running: "dm" "-usr" "admin" "-checkserver" "122" 
Wed Sep 15 07:29:23 2021: Running: "dm" "-usr" "admin" "-checkserver" "122" 
Wed Sep 15 07:29:23 2021: Capturing output
Wed Sep 15 07:29:23 2021: Waiting for command to complete
Wed Sep 15 07:29:23 2021: Exit Code: 0
```

**Comment by sbtaylor15** [comment]
Fixed in `quay.io/deployhub/deployhub-pro:ui-skin-v9.0.0.3204-g071632c`
